version: "3.8"

services:
  backend:
    container_name: node_backend
    build:
      context: ./NEOs-backend
      dockerfile: Dockerfile
    ports:
      - "4008:4008"
    restart: unless-stopped
    volumes:
      - ./NEOs-backend:/app

  frontend:
    container_name: flutter_web
    build:
      context: .  
      dockerfile: web/Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - .:/app
